### ISSUE TITLE
Functional Programming in Javascript

### ISSUE THREAD

**Issue by agarrharr** [lucasviola/awesome-functional-programming#2]
Is there a place on this list for [Functional Programming Resources in JavaScript](https://github.com/busypeoples/functional-programming-javascript)? I would put in a pull request, but I'm not sure where it would fit in.

**Comment by lucasviola** [comment]
It is a more generic list. If you want to add the repo, you can put it under repos,  if it is a Blog Post, put it under Blog Posts, and so it goes on. Or if you find it suitable you can create a new category and send the pull request so we can discuss about it :)
